### ISSUE TITLE
Pull ionic services in common modules and create AngularJS adaptors

### ISSUE THREAD

**Issue by tlvenn** [driftyco/ionic-service-core#15]
Hi,

I was thinking that all the offering you are working on has no real hard dependencies on angular.

It would be beneficial to abstract away in a common module each service and then have an adaptor for angular. Then the community can contribute different adaptors to leverage those services in other frameworks.

And for you, it means you can offer your services to a larger crowd.

Any though ?

**Comment by tlvenn** [comment]
It would also considerably easy your migration path for Angular 2 given that you will have to maintain those services for both Angular and Angular 2 for quite some time. The sooner the common code is abstracted away the better I believe.

@perrygovier or someone else from Drifty, can you comment on this plz ? Thanks !

**Comment by jskrzypek** [comment]
@Tlvenn Your best bet for getting a response is to try to get in touch with @ericb over on the [`ionic-io-testers` gitter channel](https://gitter.im/driftyco/ionic-io-testers)

**Comment by tlvenn** [comment]
Thanks @jskrzypek , will try to get in touch with him.

**Comment by ericb** [comment]
@Tlvenn The service core is the entryway into Ionic.io services, which depend on angular, specifically  the dependency on angular in the Ionic Framework, to provide a seemless integration with Ionic Apps. While it is my intention to keep code segregated between the framework and services, it is an intentional decision to rely on angular in the services code. For example, because of this dependency we are able to do some of the following:
- Auto track events in analytics
- Payload based routing in Push Notifications
- Safely rely on dependencies being loaded in an ionic app

The core is also about to take advantage of angular to provide everyone with an extremely easy way to install / configure the service libs/plugins (releasing very soon).

So while I appreciate the sentiment I don't think we will be moving away from angular with the service code. 

Having said that, our components are open sourced and so you are free to fork them and create versions which do not have dependencies on angular (though that may cause headaches when trying to integrate with other services down the line).

Feel free to reach out with any comments or suggestions in the future!
Cheers :beers:

**Comment by tlvenn** [comment]
Hi Eric,

Thanks for the response.

I honestly do feel this is a mistake given that your revenue stream will come from those services and if you can define contracts/interfaces on how to plug into those services, you just grow your potential market. There is no business reason to try to keep that ecosystem solely to Angular or Ionic.

From a technology/engineering perspective, it would be rather easy to abstract away or use listeners/events to drive the auto tracking feature you are mentioning for the analytics parts, same for the payload based routing. The last point can easily be added to angular service core adaptor. All of this can be made easily pluggable.

With Angular 2 being on the radar pretty soon, how will you handle the transition ? And how will you handle both Angular/Ionic and Angular 2 / Ionic 2 with the same code base ?

**Comment by tlvenn** [comment]
> So while I appreciate the sentiment I don't think we will be moving away from angular with the service code.

With the release of the new web client, it look like you changed your mind since then ;)

**Comment by ericb** [comment]
@Tlvenn Guilty as charged ;)
